### ISSUE TITLE
Unable to create when record exists (when it shouldn't) due to missing overwrite feature

### ISSUE THREAD

**Issue by sam-caldwell** [terraform-providers/terraform-provider-ns1#91] opened 2019-11-16 17:42 UTC
### Terraform Version
`
Terraform v0.11.6
+ provider.ns1 v1.6.0
`

### Affected Resource(s)
Please list the resources as a list, for example:
- ns1_record

### Terraform Configuration Files
```hcl
resource "ns1_record" "a___apex" {
     zone = "${var.zone_name}"
     domain = "${var.zone_name}"
     type = "ALIAS"
     ttl = 3600

     answers = {
          answer = "example.com."
     }
}
```

### Debug Output
* N/A

### Panic Output
* N/A

### Expected Behavior
1. I should have been able to specify something like OverwriteAllowed=true.
2. Terraform should have then encountered the error on create and performed an update instead.
3. Alternatively, terraform should perform a delete and create.

### Actual Behavior
1. Terraform stopped, threw an error and required manual intervention.

### Steps to Reproduce
1. Create DNS record manually, which mirrors a record in the tf configs.
2. Run `terraform apply`
3. Observe error 'record already exists'

### References
Similar to [issue #26](https://github.com/terraform-providers/terraform-provider-ns1/issues/26) for which I submitted a pull request this morning.  I'm creating this ticket so I can submit another pull request after I get lunch.

**Comment by rupa** [comment] 2019-11-18 16:15
Thanks for this issue and PR. We're thinking about it for a bit :)

**Comment by mburtless** [comment] 2019-11-26 19:51
👋 We greatly appreciate the time you've put into opening this issue and the related PR, but after some internal discussion, we've decided to close this issue.

I'm not sure if you've seen the previous PR that was contributed for this feature (#77), but this functionality has actually been discussed before and rejected.  At the time it was pointed out that, while this functionality can be found in another provider (`aws_route53_record`), it's inclusion is [viewed as an anti-pattern](https://github.com/terraform-providers/terraform-provider-aws/commit/a8c6bdfe1244f9a572b7bf15398d7137f360c83c) for Terraform, whose standard behavior requires that all resources must be imported before they can be managed by TF.

Further, the maintainers of the AWS provider were previously planning to deprecate this functionality, but had to [reverse that decision](https://github.com/terraform-providers/terraform-provider-aws/issues/7846) to support overwriting autogenerated SOA and NS records.  We have addressed that use case via the addition of an `autogenerate_ns_record` attribute in #80, so we don't feel there is a good justification remaining to introduce this behavior.

I understand that it can be painful to have to import records, if you already have a number existing in NS1 outside of TF state, but as far as Terraform is concerned, that's a feature and not a bug as it prevents operators from accidentally affecting existing infrastructure.  To ease this pain, we're considering adding support for the [terraformer](https://github.com/GoogleCloudPlatform/terraformer) project, which can generate TF state and config from your existing resources.

**Closed by mburtless** 2019-11-26 19:51 UTC

**Comment by sam-caldwell** [comment] 2019-11-27 00:47
What I ended up having to do to correct an issue was delete objects from state manually because a previous build went sideways.  This took more time for me to do manually when this feature would have allowed an automated fix.  But 🤷‍♂ I can automate this with other means.

I'd hope other customers, such as those in issue #26 might chime in with the pain this causes them.

**Comment by azamora-zsc** [comment] 2025-02-03 10:19
> 👋 We greatly appreciate the time you've put into opening this issue and the related PR, but after some internal discussion, we've decided to close this issue.
> 
> I'm not sure if you've seen the previous PR that was contributed for this feature ([#77](https://github.com/ns1-terraform/terraform-provider-ns1/pull/77)), but this functionality has actually been discussed before and rejected. At the time it was pointed out that, while this functionality can be found in another provider (`aws_route53_record`), it's inclusion is [viewed as an anti-pattern](https://github.com/terraform-providers/terraform-provider-aws/commit/a8c6bdfe1244f9a572b7bf15398d7137f360c83c) for Terraform, whose standard behavior requires that all resources must be imported before they can be managed by TF.
> 
> Further, the maintainers of the AWS provider were previously planning to deprecate this functionality, but had to [reverse that decision](https://github.com/terraform-providers/terraform-provider-aws/issues/7846) to support overwriting autogenerated SOA and NS records. We have addressed that use case via the addition of an `autogenerate_ns_record` attribute in [#80](https://github.com/ns1-terraform/terraform-provider-ns1/pull/80), so we don't feel there is a good justification remaining to introduce this behavior.
> 
> I understand that it can be painful to have to import records, if you already have a number existing in NS1 outside of TF state, but as far as Terraform is concerned, that's a feature and not a bug as it prevents operators from accidentally affecting existing infrastructure. To ease this pain, we're considering adding support for the [terraformer](https://github.com/GoogleCloudPlatform/terraformer) project, which can generate TF state and config from your existing resources.

There is another scenario where this feature would become particularly useful: AWS ACM certificate validation records. When you need to create certificates for the same domains across multiple regions (since ACM certificates are regional resources in AWS), each region creates its own validation record in Route53. This results in duplicate validation records for the same domain across different regions. The allow_overwrite attribute of the aws_route53_record resource is probably used to overcome this situation. I'm currently exploring a workaround to address this challenge effectively in NS1.
